input1=input("Enter your inputs:")
eval(input1)
input_3_3=input("Enter your second input:")
eval(input_3_3)
input_3_4=input("Enter your second input:")
eval(input_3_4)
eval(input("Enter a command: "))
