name: Checkmarx oneScan
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: sonype-01
          cx_client_id: ${{secrets.cx_client_id}}
          cx_client_secret: ${{secrets.cx_client_secret}}
   
