name: Checkmarx oneScan
  # You may pin to the exact commit or the version.
  # uses: Checkmarx/ast-github-action@f9e0e85a6c0a37f3e716007203c9db7fe17356d4
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.20
        with:
    # Provide the AST portal URL
          base_uri: https://ast.checkmarx.net/
    # Provide the Tenant for AST portal URL
          cx_tenant: sonype-01
    # Client ID for AST portal authentication
          cx_client_id: ${{secrets.cx_client_id}}
    # Secret key for AST portal authentication
          cx_client_secret: ${{secrets.cx_client_secret}}
    # Select a Checkmarx Project Name
   
